Repository SergKhram/ARES, pull requests merged in 2021-06, with the labels that each got.

#20 Fixed little problems
  src/main/kotlin/io/github/sergkhram/enrich/MarathonEnrichService.kt
Labels: bug

#21 ARES-2 - added configuration parameter for files transfering
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/kotlin/io/github/sergkhram/configuration/Configuration.kt
  src/main/kotlin/io/github/sergkhram/configuration/ConfigurationExtension.kt
  src/main/kotlin/io/github/sergkhram/enrich/CleanAllureEnrichService.kt
  src/main/kotlin/io/github/sergkhram/enrich/MarathonEnrichService.kt
  src/main/kotlin/io/github/sergkhram/utils.kt
Labels: enhancement

#22 Readme updated
  README.md
  src/main/kotlin/io/github/sergkhram/utils.kt
Labels: documentation

#31 Adding new tasks with tests execution #23
  ares-exec-plugin/build.gradle.kts
  ares-exec-plugin/src/main/kotlin/io/github/sergkhram/AresExecPlugin.kt
  ares-exec-plugin/src/main/kotlin/io/github/sergkhram/tasks/ExecutionWReportGenTask.kt
  ares-exec-plugin/src/main/kotlin/io/github/sergkhram/tasks/ExecutionWReportTask.kt
  ares-exec-plugin/src/main/kotlin/io/github/sergkhram/tasks/taskActions.kt
  ares-plugin/build.gradle.kts
  ares-plugin/src/main/kotlin/io/github/sergkhram/AresPlugin.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/AllureBlock.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/Configuration.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/ConfigurationExtension.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/MarathonBlock.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/ScreenRecordAttachment.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/TestExecutionBlock.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/enrich/CleanAllureEnrichService.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/enrich/EnrichService.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/enrich/MarathonEnrichService.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/AdbManager.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/AresLogger.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/CustomException.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/DeviceInfo.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/conditions.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/defaults.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/json.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/helpers/suspendFunctions.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/tasks/ReportGenTask.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/tasks/ReportSyncTask.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/utils.kt
  build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#32 #26 Android home as the extension property
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/Configuration.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/configuration/ConfigurationExtension.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/enrich/CleanAllureEnrichService.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/enrich/MarathonEnrichService.kt
  ares-plugin/src/main/kotlin/io/github/sergkhram/utils.kt
Labels: enhancement

#42 Wrote GitHub wiki documentation #9
  build.gradle.kts
  docs/_config.yml
  docs/_includes/ares_extension.md
  docs/_includes/content.md
  docs/_includes/properties.md
  docs/_includes/quick_start.md
  docs/_includes/tasks.md
  docs/_layouts/default.html
  docs/index.md
Labels: documentation
